project:
  type: website
  output-dir: "docs"

website:
  title: "Tea Time"
  
  navbar:
    pinned: TRUE
    search: TRUE
    # logo:
    # logo-href:
    collapse: FALSE
    left:
      - href: index.qmd
        text: Home
        icon: house-door-fill
      - href: "https://github.com/twcrockett/bobablog"
        text: Github
        icon: github
        
  page-footer:
    center: This do be our blog tee hee

format:
  html:
    theme:
      dark: darkly
      light: flatly
    # theme: www/web_report.scss
    # include-in-header:
    
    warning: FALSE
    error: TRUE
    echo: FALSE
    message: FALSE
    
    toc: FALSE
    toc-depth: 2
    toc-location: right
    
    grid:
      sidebar-width: 250px
      body-width: 950px
      margin-width: 250px

